apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 2147483648
        }
      ]
  resourceVersion: '762148'
  name: fedora-demo
  uid: 0b6e57b8-5b5a-4304-b62d-5109c11d320a
  creationTimestamp: '2025-04-07T11:12:32Z'
  generation: 1
  managedFields:
  - apiVersion: kubevirt.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      'f:metadata':
        'f:annotations':
          .: {}
          'f:vm.kubevirt.io/validations': {}
        'f:labels':
          .: {}
          'f:app': {}
          'f:kubevirt.io/dynamic-credentials-support': {}
          'f:vm.kubevirt.io/template': {}
          'f:vm.kubevirt.io/template.namespace': {}
          'f:vm.kubevirt.io/template.revision': {}
          'f:vm.kubevirt.io/template.version': {}
      'f:spec':
        .: {}
        'f:dataVolumeTemplates': {}
        'f:runStrategy': {}
        'f:template':
          .: {}
          'f:metadata':
            .: {}
            'f:annotations':
              .: {}
              'f:vm.kubevirt.io/flavor': {}
              'f:vm.kubevirt.io/os': {}
              'f:vm.kubevirt.io/workload': {}
            'f:labels':
              .: {}
              'f:kubevirt.io/domain': {}
              'f:kubevirt.io/size': {}
              'f:network.kubevirt.io/headlessService': {}
          'f:spec':
            .: {}
            'f:architecture': {}
            'f:domain':
              .: {}
              'f:cpu':
                .: {}
                'f:cores': {}
                'f:sockets': {}
                'f:threads': {}
              'f:devices':
                .: {}
                'f:disks': {}
                'f:interfaces': {}
                'f:rng': {}
              'f:features':
                .: {}
                'f:smm':
                  .: {}
                  'f:enabled': {}
              'f:firmware':
                .: {}
                'f:bootloader':
                  .: {}
                  'f:efi': {}
              'f:memory':
                .: {}
                'f:guest': {}
            'f:networks': {}
            'f:terminationGracePeriodSeconds': {}
            'f:volumes': {}
    manager: Mozilla
    operation: Update
    time: '2025-04-07T11:12:32Z'
  - apiVersion: kubevirt.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      'f:metadata':
        'f:annotations':
          'f:kubevirt.io/latest-observed-api-version': {}
          'f:kubevirt.io/storage-observed-api-version': {}
        'f:finalizers':
          .: {}
          'v:"kubevirt.io/virtualMachineControllerFinalize"': {}
    manager: virt-controller
    operation: Update
    time: '2025-04-07T11:12:32Z'
  - apiVersion: kubevirt.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      'f:status':
        'f:printableStatus': {}
        'f:runStrategy': {}
        'f:conditions': {}
        .: {}
        'f:ready': {}
        'f:volumeSnapshotStatuses': {}
        'f:observedGeneration': {}
        'f:created': {}
        'f:desiredGeneration': {}
    manager: virt-controller
    operation: Update
    subresource: status
    time: '2025-04-07T11:13:34Z'
  namespace: fedora
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  labels:
    app: fedora-demo
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.32.2
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: fedora-demo
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora-demo
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - macAddress: '02:d2:e1:00:00:0a'
            masquerade: {}
            model: virtio
            name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: fedora-demo
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: test
            chpasswd: { expire: False }
        name: cloudinitdisk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: '2025-04-07T11:13:26Z'
    status: 'True'
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: All of the VMI's DVs are bound and not running
    reason: AllDVsReady
    status: 'True'
    type: DataVolumesReady
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC fedora-demo is not shared, live migration requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: 'False'
    type: LiveMigratable
  - lastProbeTime: null
    lastTransitionTime: null
    status: 'True'
    type: StorageLiveMigratable
  - lastProbeTime: '2025-04-07T11:13:34Z'
    lastTransitionTime: null
    status: 'True'
    type: AgentConnected
  created: true
  desiredGeneration: 1
  observedGeneration: 1
  printableStatus: Running
  ready: true
  runStrategy: RerunOnFailure
  volumeSnapshotStatuses:
  - enabled: true
    name: rootdisk
  - enabled: false
    name: cloudinitdisk
    reason: 'Snapshot is not supported for this volumeSource type [cloudinitdisk]'
