apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fedora-vm
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/vm-fedora-gitops.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: vm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
